/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) casadi_fcn_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[6] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[4] = {0, 1, 0, 0};
#define s2 CASADI_PREFIX(s2)
/* model_mpc_casadi */
int model_mpc_casadi(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=7.8869999999999996e-001;
  real_t a1=arg[0] ? arg[0][0] : 0;
  a0=(a0*a1);
  a1=2.8199999999999997e-001;
  real_t a2=arg[0] ? arg[0][2] : 0;
  a1=(a1*a2);
  a0=(a0+a1);
  a1=6.4390000000000003e-001;
  real_t a3=arg[0] ? arg[0][4] : 0;
  real_t a4=(a1*a3);
  a0=(a0+a4);
  a4=1.8229999999999999e-001;
  real_t a5=arg[0] ? arg[0][5] : 0;
  real_t a6=(a4*a5);
  a0=(a0+a6);
  a6=arg[1] ? arg[1][0] : 0;
  a1=(a1*a6);
  a0=(a0+a1);
  a1=arg[1] ? arg[1][1] : 0;
  a4=(a4*a1);
  a0=(a0+a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=8.4860000000000002e-001;
  a4=arg[0] ? arg[0][1] : 0;
  a0=(a0*a4);
  a4=2.1550000000000000e-001;
  real_t a7=arg[0] ? arg[0][3] : 0;
  a4=(a4*a7);
  a0=(a0+a4);
  a4=9.7299999999999998e-002;
  real_t a8=(a4*a3);
  a0=(a0+a8);
  a8=4.8359999999999997e-001;
  real_t a9=(a8*a5);
  a0=(a0+a9);
  a4=(a4*a6);
  a0=(a0+a4);
  a8=(a8*a1);
  a0=(a0+a8);
  if (res[0]!=0) res[0][1]=a0;
  a0=6.8079999999999996e-001;
  a0=(a0*a2);
  a2=9.6570000000000000e-001;
  a8=(a2*a5);
  a0=(a0+a8);
  a2=(a2*a1);
  a0=(a0+a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=7.6539999999999997e-001;
  a0=(a0*a7);
  a7=7.3619999999999997e-001;
  a2=(a7*a3);
  a0=(a0+a2);
  a7=(a7*a6);
  a0=(a0+a7);
  if (res[0]!=0) res[0][3]=a0;
  a3=(a3+a6);
  if (res[0]!=0) res[0][4]=a3;
  a5=(a5+a1);
  if (res[0]!=0) res[0][5]=a5;
  return 0;
}

void model_mpc_casadi_incref(void) {
}

void model_mpc_casadi_decref(void) {
}

int model_mpc_casadi_n_in(void) { return 3;}

int model_mpc_casadi_n_out(void) { return 1;}

const char* model_mpc_casadi_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  default: return 0;
  }
}

const char* model_mpc_casadi_name_out(int i){
  switch (i) {
  case 0: return "o0";
  default: return 0;
  }
}

const int* model_mpc_casadi_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s1;
  case 2: return s2;
  default: return 0;
  }
}

const int* model_mpc_casadi_sparsity_out(int i) {
  switch (i) {
  case 0: return s0;
  default: return 0;
  }
}

int model_mpc_casadi_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
